
var tours = [
    {
        id: 1,
        name: "Мармароси",
        startDate: "15.05.19",
        endDate: "20.05.19",
        duration: 5,
        difficulty: 'середня',
        price: "3000",
        allPrices: ["2000","2500","3000"],
        allDates: ["12.09.2019","30.09.2019","06.10.2019"],
        currency: "грн",
        groupEmount: "5",
        shortDescription: "Some description",
        backgroungUrl: "https://lh6.googleusercontent.com/NXbwJcysamTGGpRbPig8UVr_IfexN5W3fDcQHr7oXEfr8zrCxOthi_xmPFg=w2400"
    },
    {
        id: 2,
        name: "Шпиці",
        startDate: "30.09.19",
        endDate: "03.10.19",
        duration: 4,
        difficulty: 'середня',
        price: "9400",
        currency: "грн",
        groupEmount: "10-20",
        shortDescription: "Some description",
        backgroungUrl: "https://lh6.googleusercontent.com/NXbwJcysamTGGpRbPig8UVr_IfexN5W3fDcQHr7oXEfr8zrCxOthi_xmPFg=w2400"
    },
    {
        id:3,
        name: "Грузія",
        startDate: "30.05.19",
        endDate: "15.06.19",
        duration: 14,
        difficulty: 'тяжка',
        price: "830",
        currency: "euro",
        groupEmount: "5-13",
        shortDescription: "Some description",
        backgroungUrl: "./img/img/backgroungTrip.jpg"
    },
    {
        id: 4,
        name: "Австрія",
        startDate: "13.06.19",
        endDate: "25.06.19",
        duration: 8,
        difficulty: 'середня',
        price: "1200",
        currency: "euro",
        groupEmount: "5-13",
        shortDescription: "Some description",
        backgroungUrl: "https://lh3.googleusercontent.com/JnmU-B-yrE0IjaQgnywPBVzntzrXn0DgUrco5_eay-tvRfUDnttKTYYpzbs=w2400"
    },
    {
        id: 5,
        name: "Памір",
        startDate: "30.09.19",
        endDate: "03.10.19",
        duration: 4,
        difficulty: 'легка',
        price: "9400",
        currency: "грн",
        groupEmount: "10-20",
        shortDescription: "Some description",
        backgroungUrl: "https://lh3.googleusercontent.com/hkzUXOlJbVW_ozRoJ26UsIaUMYO_jDeAL4NEWGCeQjCFEnCc5T9bHgJBit0=w2400"
    },
    {
        id: 6,
        name: "Румунія",
        startDate: "04.09.19",
        endDate: "09.10.19",
        duration: 5,
        difficulty: 'середня',
        price: "250",
        currency: "euro",
        groupEmount: "10-15",
        shortDescription: "La lallal allall alll la",
        backgroungUrl: "https://lh6.googleusercontent.com/ORZVSSWIUl77AKT6ZqvwgOzYGDFSRnDICVyuelge2zP7RZDAHZanfC1D9r0=w2400"
    },
    {
        id:7,
        name: "Parashka",
        startDate: "30.05.19",
        endDate: "15.06.19",
        duration: 14,
        difficulty: 'легка',
        price: "900",
        currency: "грн",
        groupEmount: "10-13",
        shortDescription: "Херня",
        backgroungUrl: "./img/img/backgroungTrip.jpg"
    },
];